#!/usr/bin/env ruby
# ------------------------------------------------------
# File          : chlog.rb
# Authors       : Aoran Zeng <ccmywish@qq.com>
# Created on    : <2022-03-18>
# Last modified : <2023-05-09>
#
# chlog:
#
#   Maintain your project's Changelog on the cli.
# ------------------------------------------------------

require 'chlog'

module Chlog::CLI

  def self.run

    args = $*.dup

    if args.size == 0
      help or exit
    end

    action = args[0]

    case action
    when "-h", "--help" then help or exit end

    logger = Chlog::Logger.new

    case action
    when "-g" then exit logger.generate_changelog
    when "-r" then exit logger.release_new_version(args[1])
    end

    if args[1] =~ /^--(.*)/
      logger.sub_category = $1
      logger.log = args[2..].join(' ')
    else
      logger.sub_category = nil
      logger.log = args[1..].join(' ')
    end

    case action
    when /-[nebscd]/
      logger.take_action(action)
    else
      # action =~ /^-[^-]*$/
      abort "chlog: Unknown option!"
    end
  end


  def self.help
    puts <<~EOH
    chlog (v#{Chlog::GEM_VERSION}): Help maintain the Changelog of your projects

    Usage:

      chlog -g                Generate CHANGELOG.md in git root
      chlog -r <3.14>         Release version to v3.14

    Add log:

      chlog <-main category> [--sub category] <log>

    Main Category:

      -n    Add log to New features
      -e    Add log to Enhancements
      -b    Add log to Bug fixes
      -s    Add log to Security
      -c    Add log to Compatibility
      -d    Add log to Deprecations

    EOH
  end

end

Chlog::CLI.run
